FROM python:3.12.8-bullseye

WORKDIR /app/

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY ./backend /app/backend/

COPY ./data/ /app/data/

RUN pip install "fastapi[standard]"

CMD ["python", "backend/index_data.py"]

# CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
