FROM node:22-alpine

WORKDIR /usr/src/app/frontend/

COPY ./frontend/package*.json ./

RUN npm install

COPY ./frontend /usr/src/app/frontend/

EXPOSE 8081

EXPOSE 8080

# CMD ["npm", "run", "serve"]
