FROM python:3.12.8-bullseye

WORKDIR /app/

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY ./backend /app/

COPY ./data/ /app/

RUN pip install "fastapi[standard]"

# CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
